name: "minis-projects"

services:
  back:
    container_name: back
    image: node:18-alpine
    working_dir: /app
    ports:
      - "4000:3000"
    command: npm run start:docker
    volumes:
      - ./mini-api:/app
    networks:
      - mini-network

  front:
    container_name: front
    image: node:18-alpine
    working_dir: /app
    command: npm run docker
    ports:
      - "5173:5173"
    volumes:
      - ./mini-front:/app
    networks:
      - mini-network
    environment:
      BACK_URL: http://back:3000

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: mini-db
    networks:
      - mini-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mini-network


volumes:
  db-data:
    driver: local

networks:
  mini-network:
    name: mini-network
    driver: bridge

